[build]
builder = "DOCKERFILE"
dockerfilePath = "ict_options_agent/Dockerfile"
buildArgs = []

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
numReplicas = 1
memoryMB = 256
currency = "USD"
